### ISSUE TITLE
Issues in the orginal repo

### ISSUE THREAD

**Issue by yephny** [Iamlooker/Droid-ify#66]
I've made multiple bug reports/feature requests over time, but they're all in the original repository. I'd like to have them here, but I wanted to get your opinion first as to how I should do it. I can link to those issues here; or I can copy-paste them, along with any additional comments. What do you say?

**Comment by Iamlooker** [comment]
My suggestions would be that you list all the issues which you are pointing at and add it here.

That is you can make a checklist with the links to all the old issues which are concerned :)

**Comment by yephny** [comment]
- [ ] [Search in Installed and Updates](https://github.com/NeoApplications/Neo-Store/issues/125).

- [ ] [Back up / restore the list of installed apps](https://github.com/NeoApplications/Neo-Store/issues/106)

- [ ] [The name, Droid-ify, is too generic](https://github.com/NeoApplications/Neo-Store/issues/113) and I'm going to die on this hill.

There was one more where I'd suggested an option to hide screenshots, but I don't need it anymore as I've gotten used to them.

**Comment by revuwa** [comment]
Just asking if the [first](https://github.com/NeoApplications/Neo-Store/issues/125) point is still not working for you? 
Because on my side, (app version 0.4.9) the search seems to work in all categories.

As temporarily workaround for the [second](https://github.com/NeoApplications/Neo-Store/issues/106) point you could use apps like [List My Apps](https://f-droid.org/en/packages/de.onyxbits.listmyapps/) to "export" and (manually) "restore" a list of installed apps, because I don't think that this is a common usecase, or am I wrong?

And I personally don't understand your struggle with the [app name](https://github.com/NeoApplications/Neo-Store/issues/113).
In most cases you tap on an app icon, instead for searching it by text, right?
And in case you use a text launcher, (or disable app icons) you pretty sure can tag your apps with the name you like, as I do (e. g.) for an app, that is names "Aegis" (2FA app) what is tagged with "OTP" or whatever, and can be found/executed with that.
What do you think?

**Comment by Iamlooker** [comment]
Sorry for late answer but name would not be changed, until a really strong opinion is provided or a really good name is provided

**Comment by revuwa** [comment]
So use [Izzy's repo](https://android.izzysoft.de/repo) then, to get new versions of the [app](https://android.izzysoft.de/repo/apk/com.looker.droidify) over F-Droid more frequent (as me).

I know what you meant with backup/restore scenario. What I wanted to say was, that I can't imagine, you need that feature very often. But I don't know how often you change your device for example; possible that you have that usecase way more often than me - so this was an indirect question, (if it's worth the effort to implement such a feature).

So if you like, you could name your launcher, (because I'm interested). I don't really meant rename apps, instead of tagging them, as it my launcher ([KISS](https://kisslauncher.com/)) does. I would be pretty sure that a text based launcher should have such a functionality.

**Comment by Iamlooker** [comment]
> * [ ]  [Back up / restore the list of installed apps](https://github.com/NeoApplications/Neo-Store/issues/106).

This can be merged with #19 

So I will mark this issue as marked
